### ISSUE TITLE
Autowire service fails

### ISSUE THREAD

**Issue by DrAColian** [heimrichhannot/contao-isotope-resource-booking-bundle#2]
Hey,

after a clean/fresh installation I wanted to try the resource booking bundle, but it fails with the following error:

`> @php vendor/bin/contao-setup
In DefinitionErrorExceptionPass.php line 54:
                                                                               
  Cannot autowire service "HeimrichHannot\IsotopeResourceBookingBundle\Attrib  
  ute\BookingAttribute": argument "$translator" of method "__construct()" has  
   type "Symfony\Component\Translation\TranslatorInterface" but this class was not found.`

Installed are:
Contao 4.13.6
Isotope 2.8.5
MATE Theme 2.18.0
MATE Theme + Isotope 1.2.0
with the template from the MATE Isotope Theme installed.

**Comment by koertho** [comment]
This is a symfony 5 compatiblity issue. You could change the translator interface as workaround. I can't promise a soon fix as I go on vacation.

**Comment by DrAColian** [comment]
Hey @koertho
hope you had a great vacation. Any idea if and when you might fix it?

In the meantime: I'm not really sure what to do with "change the translator interface"! Any hint, where to look or what exactly to change as workaround?

**Comment by koertho** [comment]
Hi, it's fixed in 0.1.2!
