### ISSUE TITLE
undefined method "getBookingOverview" in IsoProductContainer

### ISSUE THREAD

**Issue by DrAColian** [heimrichhannot/contao-isotope-resource-booking-bundle#3]
Hallo,

ich habe jetzt V0.1.2 auf mein Contao V4.13.8 mit Isotope V2.8.7 installiert. (Irgendwie ging das auch nicht ganz ohne Probleme, da er sich irgendwie an `require contao/conflicts: "*@dev"` gestört hat, aber nach ein bisschen basteln ging es. Der folgende Fehler tritt aber auch bei einer frischen Installation auf.)

Sobald ich ein neues Produkt mit dem Produkttyp "Verleih" anlegen will (so habe ich den genannt, der die RessourceBooking Attribute erhält), erhalte ich direkt folgenden Fehler:
`Attempted to call an undefined method named "getBookingOverview" of class "HeimrichHannot\IsotopeResourceBookingBundle\DataContainer\IsoProductContainer".`

Beste Grüße

**Comment by DrAColian** [comment]
(Reposting it in English, any idea/solution yet?)

Hey,

I've installed V0.1.2 as addon to Contao V4.13.8 with Isotope V2.8.7. (There have been some installation problems with `require contao/conflicts: "*@dev"`, but after some trial/error it worked. The following error is persistent with a completely fresh Contao installation.)

As soon as I choose "Verleih" as product type (it's the one that includes all RessourceBooking attributes) Contao stops with the following error:
`Attempted to call an undefined method named "getBookingOverview" of class "HeimrichHannot\IsotopeResourceBookingBundle\DataContainer\IsoProductContainer".`

Thanks and kind regards

**Comment by koertho** [comment]
Hi, sorry for ignoring this issue. I hope I fixed it in 0.1.3. Thanks for reporting!
