### ISSUE TITLE
Error while creating new product

### ISSUE THREAD

**Issue by DrAColian** [heimrichhannot/contao-isotope-resource-booking-bundle#4]
After fixing my previous problem, it seems, there is still something off. While selecting the product type, Contao goes throws an internal error:
`HeimrichHannot\IsotopeResourceBookingBundle\Attribute\BookingAttribute::getBookedItemsInTimeRange(): Argument #1 ($product) must be of type HeimrichHannot\IsotopeResourceBookingBundle\Attribute\ProductModel, Isotope\Model\Product\Standard given, called in /www/htdocs/w006b89d/devphoto.jooney.com/vendor/heimrichhannot/contao-isotope-resource-booking-bundle/src/Attribute/BookingAttribute.php on line 151`

Contao 4.13.16, Isotope 2.8.10

**Comment by koertho** [comment]
Should be fixed in 0.1.4. Thanks for reporting
