### ISSUE TITLE
Use for namespace missing?!

### ISSUE THREAD

**Issue by DrAColian** [heimrichhannot/contao-isotope-resource-booking-bundle#5]
I'm so sorry, to bother you again... The last error was fixed, and now I'm running into this one:

`Attempted to load class "ProductCollectionItemModel" from namespace "HeimrichHannot\IsotopeResourceBookingBundle\Attribute". Did you forget a "use" statement for another namespace?`

So, so, sorry...

**Comment by koertho** [comment]
It's not your problem. The bundle seems not beeing tested well after migration.

**Comment by koertho** [comment]
Should be fixed in 0.1.5
